name: sqlite_schema_upgrader
description: This package helps your app to upgrade your database schema every time you have to push out a new version of your app.
version: 1.0.6
repository: https://github.com/iriber/sqlite_schema_upgrader

topics:
  - sqlite
  - database

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3
  sqflite_common_ffi: ^2.3.0+2
  sqlite3: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
